In [1]:
a = 10
a

10

In [2]:
a = [1,2,4,5,6,11]
a

[1, 2, 4, 5, 6, 11]

In [6]:
import numpy as np
n = np.array(a)
n

array([ 1,  2,  4,  5,  6, 11])

In [7]:
type(n)

numpy.ndarray

In [10]:
d = np.mean(n)
print(d)

4.833333333333333

In [12]:
k = np.min(n)
k

np.int64(1)

In [14]:
k = np.max(n)
k

np.int64(11)

In [19]:
f = np.zeros([2,2])
print(f)

[[0. 0.]
 [0. 0.]]

In [21]:
f = np.ones([4,4])
f

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
g = np.random.rand(3,4)
g

array([[0.629057  , 0.24975427, 0.61137797, 0.44365713],
       [0.57333686, 0.30551109, 0.35320874, 0.64614892],
       [0.83190071, 0.26342588, 0.70085691, 0.63030252]])

In [37]:
g = np.random.randint(1,5)
g

2

In [46]:
b = [1,5,11,4,12,14,6,90,15,21,41,55,65,19,18,7,9,10]
t = np.array(b)
l = np.reshape(t,(1,18))
l

array([[ 1,  5, 11,  4, 12, 14,  6, 90, 15, 21, 41, 55, 65, 19, 18,  7,
         9, 10]])

In [45]:
x = np.arange(18).reshape(1,18)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17]])

In [58]:
g = t[10:18]
g

array([41, 55, 65, 19, 18,  7,  9, 10])

In [63]:
f = t[2:10]
f

array([11,  4, 12, 14,  6, 90, 15, 21])

In [64]:
f-g

array([-30, -51, -53,  -5, -12,  83,   6,  11])

In [65]:
f*g

array([451, 220, 780, 266, 108, 630, 135, 210])

In [68]:
x = np.array([[1,2,3],[4,5,6],[1,4,5],[9,1,4]])
y = np.array([[2,5,1,7],[4,1,7,9],[9,1,0,4]])
p = np.dot(x,y)
p

array([[37, 10, 15, 37],
       [82, 31, 39, 97],
       [63, 14, 29, 63],
       [58, 50, 16, 88]])

In [74]:
print(y)
print("Transpose Matrix:")
print(y.T)

[[2 5 1 7]
 [4 1 7 9]
 [9 1 0 4]]
Transpose Matrix:
[[2 4 9]
 [5 1 1]
 [1 7 0]
 [7 9 4]]

In [73]:
np.sort(y)

array([[1, 2, 5, 7],
       [1, 4, 7, 9],
       [0, 1, 4, 9]])

In [72]:
np.sort(x)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 4, 5],
       [1, 4, 9]])

In [91]:
a = np.array([1,6,9])
b = np.array([5,6,1,0])
c = np.concatenate((a,b))
print(c)

[1 6 9 5 6 1 0]

In [92]:
x = np.array([11,11,12,1,4,1,4,5,9,10])
k = np.unique(x)
print(k)

[ 1  4  5  9 10 11 12]

In [93]:
print(np.argmax(b))
print(np.argmin(b))

1
3

In [97]:
print(np.where(c>6))

(array([2]),)

In [98]:
print(np.cumsum(k))

[ 1  5 10 19 29 40 52]

In [99]:
np.random.randint(1,10,15)

array([9, 8, 5, 7, 8, 4, 5, 7, 8, 2, 7, 9, 1, 2, 3], dtype=int32)

In [100]:
np.save("arr.npy",c)

In [102]:
print(np.load("arr.npy"))

[1 6 9 5 6 1 0]

In [81]:
out = np.eye(4,4)
out

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [85]:
a = np.linspace(1,8,7)
a

array([1.        , 2.16666667, 3.33333333, 4.5       , 5.66666667,
       6.83333333, 8.        ])

In [104]:
a = np.array([1,5,11,4,3,12,19,10,20])
print(a[:3])

[ 1  5 11]

In [105]:
print(a[3:])

[ 4  3 12 19 10 20]

In [107]:
print(a[3::2])

[ 4 12 10]

In [108]:
print(a[:-4:])

[ 1  5 11  4  3]

In [109]:
print(a[::-1])

[20 10 19 12  3  4 11  5  1]

In [112]:
print(a[-3::])

[19 10 20]

In [114]:
x = np.array([[1,2,3],[4,5,6],[1,4,5],[9,1,4]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [1, 4, 5],
       [9, 1, 4]])

In [115]:
print(x[0:2,1:3])

[[2 3]
 [5 6]]

In [116]:
print(x[:,0:1])

[[1]
 [4]
 [1]
 [9]]

In [117]:
print(x[::2,0:2])

[[1 2]
 [1 4]]

In [118]:
print(x[1:3,::2])

[[4 6]
 [1 5]]

In [119]:
print(x[1:3:2,::2])

[[4 6]]

In [120]:
print(x[:,::2])

[[1 3]
 [4 6]
 [1 5]
 [9 4]]

In [121]:
print(x[::2,:])

[[1 2 3]
 [1 4 5]]

In [2]:
import pandas as pd

In [3]:
data = pd.read_csv("dataset.csv")
data

,Farm_ID,Current_Crop,Farm_Area(acres),Irrigation_Type,Soil_Type,Season,Previous_Crop_1,Previous_Crop_2,Previous_Crop_3,Rotation_Health_Score,...,Yield(tons),Organic_Matter_Content(%),Soil_pH,Chemical_Free_Days,Sustainability_Score,Fertilizer_Category,Pesticide_Category,Current_Fertilizer,Current_Pesticide,Sustainable_Recommendations
0,F0000,Sugarcane,370.68,Drip,Silty,Rabi,Potato,Wheat,Potato,52.5,...,186.16,4.09,5.59,255,14.89,Chemical,Chemical,MOP,Synthetic Insecticides,"{'fertilizer': 'Compost', 'transition_time': '..."
1,F0001,Maize,74.06,Manual,Clay,Zaid,Wheat,Maize,Potato,52.5,...,21.68,4.94,6.67,223,90.07,Chemical,Mixed,NPK,Limited Chemical + Neem,"{'fertilizer': 'Green Manure', 'transition_tim..."
2,F0002,Rice,203.22,Flood,Peaty,Kharif,Rice,Legumes,Maize,62.5,...,69.10,2.55,5.60,325,59.11,Chemical,Organic,NPK,Biological Control,"{'fertilizer': 'Compost', 'transition_time': '..."
3,F0003,Soybean,222.94,Rain-fed,Clay,Rabi,Rice,Soybean,Soybean,65.0,...,49.85,2.98,7.18,311,61.28,Mixed,Chemical,DAP + Vermicompost,Chemical Herbicides,"{'fertilizer': 'DAP + Vermicompost', 'transiti..."
4,F0004,Potato,67.00,Manual,Peaty,Rabi,Soybean,Wheat,Potato,62.5,...,12.41,1.34,5.50,336,85.60,Chemical,Organic,NPK,Biological Control,"{'fertilizer': 'Compost', 'transition_time': '..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4495,F4495,Barley,351.20,Drip,Sandy,Zaid,Soybean,Potato,Maize,80.0,...,63.28,4.64,7.29,285,57.59,Chemical,Chemical,MOP,Chemical Herbicides,"{'fertilizer': 'Green Manure', 'transition_tim..."
4496,F4496,Rice,491.58,Manual,Silty,Kharif,Maize,Maize,Wheat,52.5,...,147.78,2.25,6.75,15,9.17,Chemical,Chemical,Urea,Chemical Fungicides,"{'fertilizer': 'Vermicompost', 'transition_tim..."
4497,F4497,Sugarcane,76.76,Drip,Peaty,Rabi,Sugarcane,Potato,Potato,35.0,...,28.83,2.79,5.84,303,82.43,Chemical,Organic,DAP,Neem Extract,"{'fertilizer': 'Vermicompost', 'transition_tim..."
4498,F4498,Barley,82.93,Sprinkler,Silty,Rabi,Barley,Barley,Barley,17.5,...,13.02,1.68,6.04,23,78.99,Chemical,Chemical,DAP,Chemical Fungicides,"{'fertilizer': 'Bio-fertilizer', 'transition_t..."
4499,F4499,Maize,362.23,Manual,Silty,Zaid,Soybean,Maize,Potato,62.5,...,157.04,1.42,6.90,233,18.81,Mixed,Chemical,NPK + Bio-fertilizer,Chemical Fungicides,"{'fertilizer': 'NPK + Bio-fertilizer', 'transi..."

In [6]:
id = data["Farm_ID"]
id

0       F0000
1       F0001
2       F0002
3       F0003
4       F0004
        ...
4495    F4495
4496    F4496
4497    F4497
4498    F4498
4499    F4499
Name: Farm_ID, Length: 4500, dtype: str

In [7]:
x = data.loc[1:10,"Farm_ID":"Season"]
x

   Farm_ID Current_Crop  Farm_Area(acres) Irrigation_Type Soil_Type  Season
1    F0001        Maize             74.06          Manual      Clay    Zaid
2    F0002         Rice            203.22           Flood     Peaty  Kharif
3    F0003      Soybean            222.94        Rain-fed      Clay    Rabi
4    F0004       Potato             67.00          Manual     Peaty    Rabi
5    F0005       Tomato            255.43            Drip      Clay  Kharif
6    F0006        Wheat            215.90            Drip     Silty    Rabi
7    F0007        Wheat            147.10           Flood     Peaty    Zaid
8    F0008        Wheat             32.09          Manual     Silty    Rabi
9    F0009       Potato            240.79        Rain-fed     Loamy  Kharif
10   F0010       Cotton            116.43          Manual     Silty    Zaid

In [9]:
y = data["Current_Crop"]
y

0       Sugarcane
1           Maize
2            Rice
3         Soybean
4          Potato
          ...
4495       Barley
4496         Rice
4497    Sugarcane
4498       Barley
4499        Maize
Name: Current_Crop, Length: 4500, dtype: str

In [11]:
import numpy as np
u = np.unique(y)
print(u)

['Barley' 'Carrot' 'Cotton' 'Maize' 'Potato' 'Rice' 'Soybean' 'Sugarcane'
 'Tomato' 'Wheat']

In [12]:
k = u[::2]
k

array(['Barley', 'Cotton', 'Potato', 'Soybean', 'Tomato'], dtype=object)